### ISSUE TITLE
Roads on bridges

### ISSUE THREAD

**Issue by pnorman** [pnorman/osm-clear#1]
cc @math1985 from gravitystorm/openstreetmap-carto#2046

> Looks promising.
> 
> Of course the decrease in code size alone doesn't tell too much, as is for a large part achieved by removing functionality and by moving complexity to the .lua file.
> 
> I hacked the code a bit to get it to work with a standard rendering database. In my set-up, your code renders all roads on top of bridges. Does it do the same for you or is my set-up to blame?
> 
> Apart from that I don't immediately see major issues in Luxembourg.

**Comment by pnorman** [comment]
> > I hacked the code a bit to get it to work with a standard rendering database. In my set-up, your code renders all roads on top of bridges. Does it do the same for you or is my set-up to blame?

It depends on how well you adapted from the C transform tables to ClearTables. As a guess, either the conversion for `layer` or for `brunnel`is wrong.

The lua that normalizes the layer tag is

``` lua
--- Normalizes layer tags
-- @param v The layer tag value
-- @return An integer for the layer tag
function layer (v)
    return v and
        string.find(v, "^-?%d+$") and tonumber(v) < 100 and tonumber(v) > -100 and v or "0"
end
```

In SQL this would be `CASE WHEN layer '^-?\d{1,3}(\.\d+)?$' THEN ele::integer ELSE 0 END` and is similar to the layernotnull used in the osm-carto roads queries (nulls middle).

The reason `layer` is a not null integer in ClearTables is to avoid the trouble with checking for a safe cast or worrying about layer 0 where there is no layer tag ;)

If you didn't handle the case of no layer tag, NULL gets sorted like an infinitely positive number.

brunnel has two functions

``` lua
--- Normalizes a tag value to true/false
-- This is used internally for logic, and not directly returned to PostgreSQL
-- @param v The tag value
-- @return The true, false, or nil
function isset (v)
    if v == nil then
        return nil
    end
    if v == "no" or v == "false" then
        return false
    end
    return true
end
function brunnel (tags)
    return isset(tags["bridge"]) and "bridge" or isset(tags["tunnel"]) and "tunnel" or nil
end
```

Something like 

``` sql
CASE WHEN bridge IS NOT NULL AND bridge NOT IN ('no','false') THEN 'bridge'::brunnel ELSE
  CASE WHEN tunnel IS NOT NULL AND bridge NOT IN ('no','false') THEN 'tunnel'::brunnel ELSE
    NULL::brunnel
  END
END
```

would probably work.

**Comment by matthijsmelissen** [comment]
>  It depends on how well you adapted from the C transform tables to ClearTables.

Yes, probably my adaptation was wrong. Let me know if you need anything particular from me here.
